#!/usr/bin/env bash
# Install nginx n redirect to 404

sudo apt update -y
sudo apt upgrade -y
sudo apt install nginx -y
sudo service nginx start
# get hellow from server
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
# redirect to youtube video
new_string='server_name _;\n\n\trewrite \^\/redirect_me https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4 permanent;/'
sudo sed -i "s/server_name _;\$/${new_string}" /etc/nginx/sites-available/default
# redireects to 404 page
sudo sed -i "s/^\t\}$/\t\}\n\n\terror_page 404 \/404.html;/" /etc/nginx/sites-available/default
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
# restart nginx
sudo service nginx restart
