#!/usr/bin/env bash
# Installs and setup haproxy

sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.6
sudo apt-get -y update
sudo apt-get -y install haproxy=2.6.\*

echo "ENABLED=1" > /etc/default/haproxy

# Listen to 2 webservers
echo "
frontend mosweubarona.tech
	bind *:80
	stats uri /haproxy?stats
	default_backend web_servers
backend web_servers
	balance roundrobin
	server 16301-web-01 35.168.111.24:80 check
	server 16301-web-02 3.236.88.192:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy restart
