#!/usr/bin/env bash
#displays bad luck for the 4th loop iteration, good luck for the 8th & Best School for the other

x=0
while [ $x != 10 ]
do
  if [ $x = 3 ]
  then
    echo "bad luck"
  elif [ $x = 7 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  x=$(( x + 1 ))
done
